'use strict';

const path = require('path');
const acorn = require('acorn');
const run = require('test262-parser-runner');

const unsupported = [];

const implemented = ['export-default-from'];

const whitelist = [
  'language/module-code/early-dup-assert-key-export.js',
  'language/module-code/early-dup-export-as-star-as.js',
  'language/module-code/early-dup-export-decl.js',
  'language/module-code/early-dup-export-dflt-id.js',
  'language/module-code/early-dup-export-dflt.js',
  'language/module-code/early-dup-export-id-as.js',
  'language/module-code/early-dup-export-id.js',
  'language/module-code/early-dup-export-star-as-dflt.js',
  'language/module-code/early-export-global.js',
  'language/module-code/early-export-ill-formed-string.js',
  'language/module-code/early-export-unresolvable.js',
  'language/module-code/eval-export-cls-semi.js',
  'language/module-code/eval-export-dflt-cls-anon-semi.js',
  'language/module-code/eval-export-dflt-cls-anon.js',
  'language/module-code/eval-export-dflt-cls-name-meth.js',
  'language/module-code/eval-export-dflt-cls-named-semi.js',
  'language/module-code/eval-export-dflt-cls-named.js',
  'language/module-code/eval-export-dflt-expr-cls-anon.js',
  'language/module-code/eval-export-dflt-expr-cls-name-meth.js',
  'language/module-code/eval-export-dflt-expr-cls-named.js',
  'language/module-code/eval-export-dflt-expr-err-eval.js',
  'language/module-code/eval-export-dflt-expr-err-get-value.js',
  'language/module-code/eval-export-dflt-expr-fn-anon.js',
  'language/module-code/eval-export-dflt-expr-fn-named.js',
  'language/module-code/eval-export-dflt-expr-gen-anon.js',
  'language/module-code/eval-export-dflt-expr-gen-named.js',
  'language/module-code/eval-export-dflt-expr-in.js',
  'language/module-code/eval-export-dflt-fun-anon-semi.js',
  'language/module-code/eval-export-dflt-fun-named-semi.js',
  'language/module-code/eval-export-dflt-gen-anon-semi.js',
  'language/module-code/eval-export-dflt-gen-named-semi.js',
  'language/module-code/eval-export-fun-semi.js',
  'language/module-code/eval-export-gen-semi.js',
  'language/module-code/export-default-asyncfunction-declaration-binding-exists.js',
  'language/module-code/export-default-asyncfunction-declaration-binding.js',
  'language/module-code/export-default-asyncgenerator-declaration-binding-exists.js',
  'language/module-code/export-default-asyncgenerator-declaration-binding.js',
  'language/module-code/export-default-function-declaration-binding-exists.js',
  'language/module-code/export-default-function-declaration-binding.js',
  'language/module-code/export-default-generator-declaration-binding-exists.js',
  'language/module-code/export-default-generator-declaration-binding.js',
  'language/module-code/export-expname-binding-index.js',
  'language/module-code/export-expname-binding-index_FIXTURE.js',
  'language/module-code/export-expname-binding-string.js',
  'language/module-code/export-expname-from-as-unpaired-surrogate.js',
  'language/module-code/export-expname-from-binding-string.js',
  'language/module-code/export-expname-from-star-string.js',
  'language/module-code/export-expname-from-star-unpaired-surrogate.js',
  'language/module-code/export-expname-from-star.js',
  'language/module-code/export-expname-from-string-binding.js',
  'language/module-code/export-expname-from-string-string.js',
  'language/module-code/export-expname-from-string.js',
  'language/module-code/export-expname-from-unpaired-surrogate.js',
  'language/module-code/export-expname-import-string-binding.js',
  'language/module-code/export-expname-import-unpaired-surrogate.js',
  'language/module-code/export-expname-string-binding.js',
  'language/module-code/export-expname-unpaired-surrogate.js',
  'language/module-code/export-expname_FIXTURE.js',
  'language/module-code/export-star-as-dflt.js',
  'language/module-code/export-star-as-dflt_FIXTURE.js',
  'language/module-code/instn-local-bndng-export-cls.js',
  'language/module-code/instn-local-bndng-export-const.js',
  'language/module-code/instn-local-bndng-export-fun.js',
  'language/module-code/instn-local-bndng-export-gen.js',
  'language/module-code/instn-local-bndng-export-let.js',
  'language/module-code/instn-local-bndng-export-var.js',
  'language/module-code/instn-resolve-empty-export.js',
  'language/module-code/instn-resolve-empty-export_FIXTURE.js',
  'language/module-code/instn-star-props-dflt-keep-indirect-reexport_FIXTURE.js',
  'language/module-code/parse-err-decl-pos-export-arrow-function.js',
  'language/module-code/parse-err-decl-pos-export-block-stmt-list.js',
  'language/module-code/parse-err-decl-pos-export-block-stmt.js',
  'language/module-code/parse-err-decl-pos-export-class-decl-meth-static.js',
  'language/module-code/parse-err-decl-pos-export-class-decl-meth.js',
  'language/module-code/parse-err-decl-pos-export-class-decl-method-gen-static.js',
  'language/module-code/parse-err-decl-pos-export-class-decl-method-gen.js',
  'language/module-code/parse-err-decl-pos-export-class-expr-meth-gen-static.js',
  'language/module-code/parse-err-decl-pos-export-class-expr-meth-gen.js',
  'language/module-code/parse-err-decl-pos-export-class-expr-meth-static.js',
  'language/module-code/parse-err-decl-pos-export-class-expr-meth.js',
  'language/module-code/parse-err-decl-pos-export-do-while.js',
  'language/module-code/parse-err-decl-pos-export-for-const.js',
  'language/module-code/parse-err-decl-pos-export-for-in-const.js',
  'language/module-code/parse-err-decl-pos-export-for-in-let.js',
  'language/module-code/parse-err-decl-pos-export-for-in-lhs.js',
  'language/module-code/parse-err-decl-pos-export-for-in-var.js',
  'language/module-code/parse-err-decl-pos-export-for-let.js',
  'language/module-code/parse-err-decl-pos-export-for-lhs.js',
  'language/module-code/parse-err-decl-pos-export-for-of-const.js',
  'language/module-code/parse-err-decl-pos-export-for-of-let.js',
  'language/module-code/parse-err-decl-pos-export-for-of-lhs.js',
  'language/module-code/parse-err-decl-pos-export-for-of-var.js',
  'language/module-code/parse-err-decl-pos-export-for-var.js',
  'language/module-code/parse-err-decl-pos-export-function-decl.js',
  'language/module-code/parse-err-decl-pos-export-function-expr.js',
  'language/module-code/parse-err-decl-pos-export-generator-decl.js',
  'language/module-code/parse-err-decl-pos-export-generator-expr.js',
  'language/module-code/parse-err-decl-pos-export-if-else.js',
  'language/module-code/parse-err-decl-pos-export-if-if.js',
  'language/module-code/parse-err-decl-pos-export-labeled.js',
  'language/module-code/parse-err-decl-pos-export-object-gen-method.js',
  'language/module-code/parse-err-decl-pos-export-object-getter.js',
  'language/module-code/parse-err-decl-pos-export-object-method.js',
  'language/module-code/parse-err-decl-pos-export-object-setter.js',
  'language/module-code/parse-err-decl-pos-export-switch-case-dflt.js',
  'language/module-code/parse-err-decl-pos-export-switch-case.js',
  'language/module-code/parse-err-decl-pos-export-switch-dftl.js',
  'language/module-code/parse-err-decl-pos-export-try-catch-finally.js',
  'language/module-code/parse-err-decl-pos-export-try-catch.js',
  'language/module-code/parse-err-decl-pos-export-try-finally.js',
  'language/module-code/parse-err-decl-pos-export-try-try.js',
  'language/module-code/parse-err-decl-pos-export-while.js',
  'language/module-code/parse-err-export-dflt-const.js',
  'language/module-code/parse-err-export-dflt-expr.js',
  'language/module-code/parse-err-export-dflt-let.js',
  'language/module-code/parse-err-export-dflt-var.js',
  'language/module-code/parse-err-semi-export-star.js',
  'language/module-code/parse-err-semi-name-space-export.js',
  'language/module-code/parse-err-semi-named-export-from.js',
  'language/module-code/parse-err-semi-named-export.js',
  'language/module-code/parse-export-empty.js',
].map((spec) => [`${spec} (default)`, `${spec} (strict mode)`]).reduce(spec => [...spec]);

const Parser = acorn.Parser.extend(require('../dist'));

module.exports = function() {
  run(
    (content, options) => Parser.parse(content, { sourceType: options.sourceType, ecmaVersion: 13 }),
    {
      testsDirectory: path.dirname(require.resolve('test262/package.json')),
      skip: (test) =>
        !test.attrs.features ||
        ! implemented.some((feature) => tests.attrs.features.includes(feature)) ||
        unsupported.some((feature) => tests.attrs.features.includes(feature)),
      whitelist,
    }
  );
}
